class Product {
  final int id;
  final String name;
  final double price;
  final double rating;
  final String category;
  final String icon;
  final String unit;

  Product({
    required this.id,
    required this.name,
    required this.price,
    required this.rating,
    required this.category,
    required this.icon,
    required this.unit,
  });

  static const List<String> categories = [
    'Fresh Fruits',
    'Vegetables',
    'Dairy',
    'Bakery',
    'Snacks',
  ];

  static final List<Product> sampleProducts = [
    Product(
      id: 1,
      name: 'Fresh Apples',
      price: 4.99,
      rating: 4.8,
      category: 'Fresh Fruits',
      icon: '🍎',
      unit: 'kg',
    ),
    Product(
      id: 2,
      name: 'Bananas',
      price: 2.99,
      rating: 4.9,
      category: 'Fresh Fruits',
      icon: '🍌',
      unit: 'kg',
    ),
    Product(
      id: 3,
      name: 'Oranges',
      price: 3.49,
      rating: 4.7,
      category: 'Fresh Fruits',
      icon: '🍊',
      unit: 'kg',
    ),
    Product(
      id: 4,
      name: 'Strawberries',
      price: 5.99,
      rating: 4.9,
      category: 'Fresh Fruits',
      icon: '🍓',
      unit: 'pack',
    ),
    Product(
      id: 5,
      name: 'Carrots',
      price: 1.99,
      rating: 4.7,
      category: 'Vegetables',
      icon: '🥕',
      unit: 'kg',
    ),
    Product(
      id: 6,
      name: 'Broccoli',
      price: 3.49,
      rating: 4.6,
      category: 'Vegetables',
      icon: '🥦',
      unit: 'pc',
    ),
    Product(
      id: 7,
      name: 'Tomatoes',
      price: 2.79,
      rating: 4.8,
      category: 'Vegetables',
      icon: '🍅',
      unit: 'kg',
    ),
    Product(
      id: 8,
      name: 'Lettuce',
      price: 1.99,
      rating: 4.5,
      category: 'Vegetables',
      icon: '🥬',
      unit: 'pc',
    ),
    Product(
      id: 9,
      name: 'Fresh Milk',
      price: 3.99,
      rating: 4.9,
      category: 'Dairy',
      icon: '🥛',
      unit: 'L',
    ),
    Product(
      id: 10,
      name: 'Yogurt',
      price: 2.49,
      rating: 4.8,
      category: 'Dairy',
      icon: '🥣',
      unit: 'pc',
    ),
    Product(
      id: 11,
      name: 'Cheese',
      price: 5.99,
      rating: 4.7,
      category: 'Dairy',
      icon: '🧀',
      unit: 'pack',
    ),
    Product(
      id: 12,
      name: 'Butter',
      price: 4.49,
      rating: 4.6,
      category: 'Dairy',
      icon: '🧈',
      unit: 'pack',
    ),
    Product(
      id: 13,
      name: 'Fresh Bread',
      price: 2.99,
      rating: 4.7,
      category: 'Bakery',
      icon: '🍞',
      unit: 'pc',
    ),
    Product(
      id: 14,
      name: 'Croissant',
      price: 1.99,
      rating: 4.8,
      category: 'Bakery',
      icon: '🥐',
      unit: 'pc',
    ),
    Product(
      id: 15,
      name: 'Bagels',
      price: 3.49,
      rating: 4.6,
      category: 'Bakery',
      icon: '🥯',
      unit: 'pack',
    ),
    Product(
      id: 16,
      name: 'Donuts',
      price: 4.99,
      rating: 4.9,
      category: 'Bakery',
      icon: '🍩',
      unit: 'pack',
    ),
    Product(
      id: 17,
      name: 'Cookies',
      price: 3.99,
      rating: 4.8,
      category: 'Snacks',
      icon: '🍪',
      unit: 'pack',
    ),
    Product(
      id: 18,
      name: 'Chips',
      price: 2.99,
      rating: 4.7,
      category: 'Snacks',
      icon: '🥔',
      unit: 'pack',
    ),
    Product(
      id: 19,
      name: 'Popcorn',
      price: 2.49,
      rating: 4.6,
      category: 'Snacks',
      icon: '🍿',
      unit: 'pack',
    ),
    Product(
      id: 20,
      name: 'Chocolate',
      price: 4.99,
      rating: 4.9,
      category: 'Snacks',
      icon: '🍫',
      unit: 'pack',
    ),
  ];
}